### ISSUE TITLE
Small typo in linuxtv-dvb-apps

### ISSUE THREAD

**Issue by tatokis** [tmn505/AUR#2]
There's a small typo in the optdepends section in the linuxtv-dvb-apps PKGBUILD.

https://github.com/tmn505/AUR/blob/a91fe2effbe78113d4849f885fb513077862fb52/linuxtv-dvb-apps/PKGBUILD#L18

It should be `scanning` instead of `scannig`

**Comment by tmn505** [comment]
Hi,
as this package is not maintained by me any more, I removed it and sent fix to current maintainer(s) https://github.com/VDR4Arch/vdr4arch/pull/213/commits/89c2f247051e1eda9323add9f072fb68ce84e1ce.

**Comment by tatokis** [comment]
Thank you!
