### ISSUE TITLE
Add brscan4 as a dependency

### ISSUE THREAD

**Issue by ghost** [tmn505/AUR#3]
The brother-dcp-l2500d AUR package does not contain the optional dependency on brscan4, due to this the users have to manually search for the supported scanner driver.
Could you add it as an optional dependency?

For references see this package: https://aur.archlinux.org/packages/brother-dcpl2530dw/

**Comment by tmn505** [comment]
Yeah, there are few brscan versions, so pointing to the right one is useful.
Fixed with https://github.com/tmn505/AUR/commit/a971002b2fa7aeec2bf7af6981872245687d91d7

**Comment by ghost** [comment]
Thank you!
